### ISSUE TITLE
Use logging.exception instead of traceback.format_exc 

### ISSUE THREAD

**Issue by bokchan** [GDay/django-q2#41]
`traceback.format_exc` is used in the `pusher` function to log exceptions, e.g https://github.com/GDay/django-q2/blob/master/django_q/cluster.py#L370 

Unfortunately this can raise an additional error: `TypeError: not all arguments converted during string formatting`

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
```

To avoid this it is suggested to use `logger.exception` instead as this will include the traceback and avoid the TypeError.

**Comment by GDay** [comment]
Closed by #42
