### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by eugenewere** [GDay/django-q2#46]
```
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Connection.disconnect() done, defined at /home/yyyyy/project/code/yyy/yyy/env/lib/python3.10/site-packages/redis/asyncio/connection.py:815> exception=RuntimeError('Event loop is closed')>
Traceback (most recent call last):
  File "/home/yyyy/project/code/yyyy/yyyy/env/lib/python3.10/site-packages/redis/asyncio/connection.py", line 824, in disconnect
    self._writer.close()  # type: ignore[union-attr]
  File "/usr/lib/python3.10/asyncio/streams.py", line 337, in close
    return self._transport.close()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 753, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

Found this Error. Either its redis or django q2
Am using redis:7.0.5 
django 3.2.16
django q2  1.4.6
redis-py 4.4.0

**Comment by GDay** [comment]
Are you using more libraries than those? Could you check if you are using `channels-redis` perhaps? (normally you can get a full list with `pip freeze`, unless you use a different package manager).

Looks very similar to this issue: https://github.com/django/channels_redis/issues/332

And this seems to fix it: https://github.com/django/channels_redis/issues/332#issuecomment-1325531466

**Comment by eugenewere** [comment]
Ohh yes am using channel redis
`channels-redis==4.0.0`
`channels==4.0.0`
